theme: jekyll-theme-tactile
show_downloads: true
github:
  zip_url: https://github.com/MuhdNurHidayat/unicodeparser/archive/master.zip
  tar_url: https://github.com/MuhdNurHidayat/unicodeparser/archive/master.tar.gz
